on:
    push:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   uses: docker/setup-qemu-action@v2

            -   uses: docker/setup-buildx-action@v2

            -   uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            -   uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ github.repository }}:latest